### ISSUE TITLE
decoder.py error

### ISSUE THREAD

**Issue by ajengwulandari** [YuhangMing/visual-attention-image-caption#1]
I got this error when I run decoder.py:

Traceback (most recent call last):
  File "decoder.py", line 150, in <module>
    cap = random.choice(captions['train'][idx])
NameError: name 'idx' is not defined

Can you help me? Thanks

**Comment by YuhangMing** [comment]
Hi Ajeng,

Sorry I forgot to update the main function in the decoder.py file. I wrote a main there only for debugging.
You can set idx to be any integer with the range.

Best,
Yuhang
